[features]
seeds = false
skip-lint = false

[programs.localnet]
git_to_earn = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
git_to_earn = "8KFc1kae5g8LqAwmZHskgaSYjaHXpt9PCRwKNtuajgAa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/adithyanarayan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
